# Generated by Django 4.2.3 on 2023-07-20 00:14

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization_level', '0001_initial'),
        ('organization_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default=None, max_length=128, null=True, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None, unique=True)),
                ('representative', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('level', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_places', to='organization_level.organizationlevel')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities_places', to='activities_place.activitiesplace')),
                ('type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_places', to='organization_type.organizationtype')),
            ],
            options={
                'db_table': 'activities_places',
                'ordering': ['name'],
            },
        ),
    ]
