# Generated by Django 4.2.3 on 2023-07-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitiesplace',
            name='representative',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
