# Generated by Django 4.2.3 on 2023-07-20 09:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_place', '0002_alter_activitiesplace_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitiesplace',
            name='parent_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
