# Generated by Django 4.2.3 on 2023-07-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(1, 'Single choice'), (2, 'Multiple choices')], default=1),
        ),
    ]
