# Generated by Django 4.2.3 on 2023-07-27 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_alter_contest_cover_image'),
        ('question', '0002_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='contest.contest'),
        ),
    ]
