# Generated by Django 4.2.3 on 2023-07-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_by',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_by',
            field=models.IntegerField(default=1),
        ),
    ]
