# Generated by Django 4.2.3 on 2023-07-19 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsCategory', '0001_initial'),
        ('news', '0002_alter_news_created_by_alter_news_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='newsCategory.newscategory'),
            preserve_default=False,
        ),
    ]
