# Generated by Django 4.2.3 on 2023-07-19 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_initial'),
        ('news', '0004_alter_news_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_by', to='staff.staff'),
        ),
    ]
