# Generated by Django 4.2.3 on 2023-07-21 15:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_created_by_alter_news_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_category_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
