# Generated by Django 4.2.3 on 2023-07-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_news_category_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_category',
        ),
    ]
