# Generated by Django 4.2.3 on 2023-07-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
