# Generated by Django 4.2.3 on 2023-07-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_exam_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='submitted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
