# Generated by Django 4.2.3 on 2023-07-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_exam_submitted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-id'], 'permissions': (('submit', 'Nộp bài'),)},
        ),
    ]
