# Generated by Django 4.2.3 on 2023-07-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_exam_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-id'], 'permissions': (('submit_exam', 'Nộp bài'),)},
        ),
    ]
