# Generated by Django 4.2.3 on 2023-07-28 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_alter_contest_cover_image'),
        ('member', '0007_alter_member_dob_alter_member_education_level_and_more'),
        ('exam', '0007_alter_exam_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='contest.contest'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='member.member'),
        ),
    ]
