# Generated by Django 4.2.3 on 2023-07-25 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam_question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('correct', models.BooleanField()),
                ('exam_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_question.examquestion')),
            ],
            options={
                'db_table': 'exam_answers',
                'ordering': ['-id'],
            },
        ),
    ]
