# Generated by Django 4.2.3 on 2023-07-27 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_question', '0003_alter_examquestion_exam'),
        ('exam_answer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examanswer',
            name='exam_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_answers', to='exam_question.examquestion'),
        ),
    ]
