# Generated by Django 4.2.3 on 2023-07-25 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0003_staff_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField(default='')),
                ('cover_image', models.CharField(default='', max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='staff.staff')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to='staff.staff')),
            ],
            options={
                'db_table': 'news',
                'ordering': ['-id'],
            },
        ),
    ]
