# Generated by Django 4.2.3 on 2023-07-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cover_image',
            field=models.TextField(default=''),
        ),
    ]
