# Generated by Django 4.2.3 on 2023-07-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.IntegerField(choices=[(1, 'Không hiệu lực'), (2, 'Hiệu lực')], default=2),
        ),
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.IntegerField(choices=[(1, 'Tin thường'), (2, 'Tin nổi bật')], default=1),
        ),
    ]
