# Generated by Django 4.2.3 on 2023-07-26 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_status_alter_news_type'),
        ('news', '0004_alter_news_title'),
    ]

    operations = [
    ]
