# Generated by Django 4.2.3 on 2023-07-21 14:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsCategory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_type', to='newsCategory.newscategory'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='parent_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='name',
            field=models.CharField(db_collation='und-x-icu', max_length=255),
        ),
    ]
