# Generated by Django 4.2.3 on 2023-07-21 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsCategory', '0002_newscategory_parent_newscategory_parent_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='newsCategory.newscategory'),
        ),
    ]
