# Generated by Django 4.2.3 on 2023-07-19 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education_level', '__first__'),
        ('political_theory_level', '__first__'),
        ('ethnic', '__first__'),
        ('occupation', '__first__'),
        ('position', '__first__'),
        ('qualification', '__first__'),
        ('religion', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foreign_language_level', '__first__'),
        ('it_level', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('gender', models.IntegerField(choices=[(0, 'Nữ'), (1, 'Nam')], null=True)),
                ('identity_number', models.CharField(max_length=255)),
                ('participated_place_id', models.IntegerField()),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('issued_place', models.CharField(max_length=255)),
                ('education_level', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='union_members', to='education_level.educationlevel')),
                ('ethnic', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='union_members', to='ethnic.ethnic')),
                ('foreign_language_level', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='union_members', to='foreign_language_level.foreignlanguagelevel')),
                ('it_level', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='union_members', to='it_level.itlevel')),
                ('occupation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='union_members', to='occupation.occupation')),
                ('political_theory_level', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='union_members', to='political_theory_level.politicaltheorylevel')),
                ('position', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='union_members', to='position.position')),
                ('qualification', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='union_members', to='qualification.qualification')),
                ('religion', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='union_members', to='religion.religion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'union_members',
                'ordering': ['-user'],
            },
        ),
    ]
