# Generated by Django 4.2.3 on 2023-07-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('union_member', '0002_unionmember_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unionmember',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
