# Generated by Django 4.2.3 on 2023-07-20 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities_place', '0003_activitiesplace_parent_ids'),
        ('union_member', '0002_unionmember_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unionmember',
            name='activities_place',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='union_members', to='activities_place.activitiesplace'),
        ),
    ]
