# Generated by Django 4.2.3 on 2023-07-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('union_member', '0004_unionmember_place_of_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='unionmember',
            name='place_of_residence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
