# Generated by Django 4.2.3 on 2023-07-20 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('union_member', '0003_unionmember_activities_place'),
        ('union_member', '0005_unionmember_place_of_residence'),
    ]

    operations = [
    ]
