# Generated by Django 4.2.3 on 2023-07-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('union_member', '0003_unionmember_organization'),
        ('union_member', '0006_merge_20230720_1002'),
    ]

    operations = [
    ]
