# Generated by Django 4.2.3 on 2023-07-21 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('union_member', '0007_merge_20230720_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unionmember',
            name='participated_place_id',
        ),
    ]
