# Generated by Django 4.2.3 on 2023-07-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organization_rep_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
