# Generated by Django 4.2.3 on 2023-07-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_organization_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='level',
            field=models.IntegerField(choices=[(1, 'Thành phố'), (2, 'Quận (và tương đương)'), (3, 'Đoàn giao quyền cấp trên cơ sở'), (4, 'Đoàn cơ sở / Chi Đoàn cơ sở / Liên chi Đoàn'), (5, 'Chi Đoàn')], default=1),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rep_email',
            field=models.EmailField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.IntegerField(choices=[(1, 'Khối doanh nghiệp nhà nước'), (2, 'Khối doanh nghiệp ngoài nhà nước'), (3, 'Khối công chức, viên chức'), (4, 'Khối lực lượng, vũ trang'), (5, 'Khối trường học'), (6, 'Khối đô thị'), (7, 'Khối nông thôn'), (8, 'Khối cơ quan và doanh nghiệp')], default=1),
        ),
    ]
