# Generated by Django 4.2.3 on 2023-07-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_organization_root_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='rep_mobile',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
