# Generated by Django 4.2.3 on 2023-07-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
    ]
