# Generated by Django 4.2.3 on 2023-07-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_alter_contest_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contest_organizer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='number_of_question',
            field=models.IntegerField(default=1),
        ),
    ]
