# Generated by Django 4.2.3 on 2023-07-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_contest_contest_organizer_contest_number_of_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
