# Generated by Django 4.2.3 on 2023-07-18 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsType', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newstype',
            table='news_types',
        ),
    ]
