# Generated by Django 4.2.3 on 2023-07-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsType', '0004_alter_newstype_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
