# Generated by Django 4.2.3 on 2023-07-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsType', '0005_alter_newstype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstype',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
