# Generated by Django 4.2.3 on 2023-07-21 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsType', '0006_newstype_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstype',
            name='order_id',
        ),
    ]
