# Generated by Django 4.2.3 on 2023-07-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsType', '0007_remove_newstype_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstype',
            name='name',
            field=models.CharField(db_collation='und-x-icu', max_length=255),
        ),
    ]
