# Generated by Django 4.2.3 on 2023-07-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='source_type',
            field=models.IntegerField(choices=[(1, 'Tin tức'), (2, 'Đợt tình nguyện'), (3, 'Cuộc thi')], default=1),
        ),
    ]
