# Generated by Django 4.2.3 on 2023-07-27 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_alter_member_dob_alter_member_education_level_and_more'),
        ('message', '0002_alter_message_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='member',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='member.member'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
