# Generated by Django 4.2.3 on 2023-07-25 12:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0003_staff_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('cover_image', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('content', models.TextField()),
                ('place', models.CharField(max_length=255)),
                ('registration_from', models.DateTimeField()),
                ('registration_to', models.DateTimeField()),
                ('occurring_time', models.CharField(max_length=255)),
                ('beneficiaries', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('status', models.IntegerField()),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_created_by', to='staff.staff')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_updated_by', to='staff.staff')),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-id'],
            },
        ),
    ]
