# Generated by Django 4.2.3 on 2023-07-25 12:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_alter_campaign_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='beneficiaries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
