# Generated by Django 4.2.3 on 2023-07-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_alter_campaign_beneficiaries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='beneficiaries',
            new_name='beneficiary_types',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='type',
            field=models.IntegerField(choices=[(1, 'Hiến máu'), (2, 'Giúp đỡ người già'), (2, 'Giảng dạy'), (2, 'Trồng cây')], default=1),
        ),
    ]
