# Generated by Django 4.2.3 on 2023-07-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_rename_beneficiaries_campaign_beneficiary_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='type',
            field=models.IntegerField(choices=[(1, 'Hiến máu'), (2, 'Giúp đỡ người già'), (3, 'Giảng dạy'), (4, 'Trồng cây')], default=1),
        ),
    ]
