# Generated by Django 4.2.3 on 2023-07-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examquestion',
            old_name='question_type',
            new_name='type',
        ),
    ]
