# Generated by Django 4.2.3 on 2023-07-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_attachment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignattachment',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='campaignattachment',
            name='type',
            field=models.IntegerField(choices=[(1, 'Ảnh'), (2, 'Tệp tài liệu')], default=1),
        ),
    ]
