# Generated by Django 4.2.3 on 2023-07-27 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_rename_beneficiaries_campaign_beneficiary_types_and_more'),
        ('campaign_attachment', '0002_alter_campaignattachment_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignattachment',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_attachments', to='campaign.campaign'),
        ),
    ]
