# Generated by Django 4.2.3 on 2023-07-25 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0002_alter_member_education_level_alter_member_ethnic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('ios', 'ios'), ('android', 'android')], max_length=20, null=True)),
                ('registration_token', models.TextField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='member.member')),
            ],
            options={
                'db_table': 'device_tokens',
                'ordering': ['-id'],
            },
        ),
    ]
