# Generated by Django 4.2.3 on 2023-07-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0003_alter_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
