# Generated by Django 4.2.3 on 2023-07-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0004_answer_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-order']},
        ),
    ]
