# Generated by Django 4.2.3 on 2023-07-27 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0005_alter_answer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['order']},
        ),
    ]
