# Generated by Django 4.2.3 on 2023-07-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_dob_member_place_of_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Nữ'), (1, 'Nam')], null=True),
        ),
    ]
