# Generated by Django 4.2.3 on 2023-07-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_member_education_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ethnic',
            field=models.IntegerField(blank=True, choices=[(1, 'Kinh'), (2, 'Mường'), (3, 'Ê đê'), (4, 'Thổ'), (5, 'Tày'), (6, 'Ra Glai'), (7, 'Nùng'), (8, 'Bố Y'), (9, 'Lào'), (10, 'Thái'), (11, 'Mông'), (12, 'Giáy'), (13, 'Chăm'), (14, 'Lự'), (15, 'Dao'), (16, 'Mèo'), (17, 'Mnông'), (18, 'Sán Chay'), (19, 'Jrai'), (20, 'Cờ Lao'), (21, 'La Chí'), (22, 'La Ha'), (23, 'Pu Péo'), (24, 'Ba Na'), (25, 'Brâu'), (26, 'Bru - Vân Kiều'), (27, 'Chơ Ro'), (28, 'Cơ Ho'), (29, 'Cơ Tu'), (30, 'Gỉe Triêng'), (31, 'Hrê'), (32, 'Kháng'), (33, 'Khơ Me'), (34, 'Khơ Mú'), (35, 'Mạ'), (36, 'Mảng'), (37, 'Ơ Đu'), (38, 'Rơ Măm'), (39, 'Tà Ôi'), (40, 'Xinh Mun'), (41, 'Xinh Mun'), (42, 'Xơ Đăng'), (43, 'S Tiêng'), (44, 'Pà Thẻn'), (45, 'Chu Ru'), (46, 'Hoa'), (47, 'Ngái'), (48, 'Sán Dìu'), (49, 'Cống'), (50, 'Hà Nhì'), (51, 'La Hủ'), (52, 'Lô Lô'), (53, 'Phú Lá'), (54, 'Si La'), (55, 'Co'), (56, 'Sán Chỉ'), (57, 'T’Rin'), (58, 'Cadong'), (59, 'Chứt'), (60, 'Jarai'), (61, 'Không xác định'), (62, 'Cao Lan')], null=True),
        ),
    ]
