# Generated by Django 4.2.3 on 2023-07-26 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occupation', '0001_initial'),
        ('organization', '0005_alter_organization_level_and_more'),
        ('position', '0001_initial'),
        ('member', '0006_alter_member_ethnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dob',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='education_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Tiểu học'), (2, 'Trung học cơ sở'), (3, 'Trung học phổ thông hệ 10/10'), (4, 'Hệ 12/12')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='ethnic',
            field=models.IntegerField(blank=True, choices=[(1, 'Kinh'), (2, 'Mường'), (3, 'Ê đê'), (4, 'Thổ'), (5, 'Tày'), (6, 'Ra Glai'), (7, 'Nùng'), (8, 'Bố Y'), (9, 'Lào'), (10, 'Thái'), (11, 'Mông'), (12, 'Giáy'), (13, 'Chăm'), (14, 'Lự'), (15, 'Dao'), (16, 'Mèo'), (17, 'Mnông'), (18, 'Sán Chay'), (19, 'Jrai'), (20, 'Cờ Lao'), (21, 'La Chí'), (22, 'La Ha'), (23, 'Pu Péo'), (24, 'Ba Na'), (25, 'Brâu'), (26, 'Bru - Vân Kiều'), (27, 'Chơ Ro'), (28, 'Cơ Ho'), (29, 'Cơ Tu'), (30, 'Gỉe Triêng'), (31, 'Hrê'), (32, 'Kháng'), (33, 'Khơ Me'), (34, 'Khơ Mú'), (35, 'Mạ'), (36, 'Mảng'), (37, 'Ơ Đu'), (38, 'Rơ Măm'), (39, 'Tà Ôi'), (40, 'Xinh Mun'), (41, 'Xinh Mun'), (42, 'Xơ Đăng'), (43, 'S Tiêng'), (44, 'Pà Thẻn'), (45, 'Chu Ru'), (46, 'Hoa'), (47, 'Ngái'), (48, 'Sán Dìu'), (49, 'Cống'), (50, 'Hà Nhì'), (51, 'La Hủ'), (52, 'Lô Lô'), (53, 'Phú Lá'), (54, 'Si La'), (55, 'Co'), (56, 'Sán Chỉ'), (57, 'T’Rin'), (58, 'Cadong'), (59, 'Chứt'), (60, 'Jarai'), (61, 'Không xác định'), (62, 'Cao Lan')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='foreign_language_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Bậc 1'), (2, 'Bậc 2'), (3, 'Bậc 3'), (4, 'Bậc 4'), (5, 'Bậc 5'), (6, 'Bậc 6')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Nữ'), (1, 'Nam')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='id_issued_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='it_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Chuẩn kỹ năng sử dụng CNTT cơ bản'), (2, 'Chuẩn kỹ năng sử dụng CNTT nâng cao')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='joined_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='occupation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='occupation.occupation'),
        ),
        migrations.AlterField(
            model_name='member',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='member',
            name='place_of_origin',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='place_of_residence',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='political_theory_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Sơ cấp'), (2, 'Trung cấp'), (3, 'Cao cấp'), (4, 'Cử nhân'), (5, 'Chưa có')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='position.position'),
        ),
        migrations.AlterField(
            model_name='member',
            name='qualification',
            field=models.IntegerField(blank=True, choices=[(1, 'Sơ cấp'), (2, 'Trung cấp chuyên nghiệp'), (3, 'Cao đẳng'), (4, 'Cử nhân'), (5, 'Thạc sĩ'), (6, 'Tiến sĩ')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='religion',
            field=models.IntegerField(blank=True, choices=[(1, 'Tin Lành'), (2, 'Không'), (3, 'Cao Đài'), (4, 'Công giáo'), (5, 'Phật giáo'), (6, 'Hòa Hảo'), (7, 'Hồi giáo'), (8, "Bahá'í"), (9, 'Bà La Môn'), (10, 'Đạo Tứ ấn hiếu nghĩa'), (11, 'Tịnh độ cư sĩ Phật hội Việt Nam'), (12, 'Bửu sơn Kỳ hương'), (13, 'Minh Sư Đạo'), (14, 'Minh Lý Đạo')], default=2, null=True),
        ),
    ]
